allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.11.22
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  sharp@<0.35.4: 0.35.4
  baseline-browser-mapping@<2.11.0: 2.11.22
