import UploadFile from '@/components/UploadFile/UploadFile'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col justify-center items-center h-screen w-full bg-slate-900'>
        <h1 className='text-3xl font-bold text-white my-8'>
          ✨Custom<span className='text-pink-700'>Avatar</span>
        </h1>
        <UploadFile />
      </main>
    </>
  )
}
